### PR TITLE
[118] - Added Flutter send build info to telegram chat

### PR DESCRIPTION
**Pull request by KirBorisov96**

### CODE REVIEW

**Comment by KirBorisov96** [comment]
Platform: iOS
Build ID: 11
Version: 1669705420
Internal Version: 0
Short Version: 1.0.0
Branch Name: feature/118-flutter-telegram-build-info
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-Flutter-iOS-Dev/releases/11

**Comment by KirBorisov96** [comment]
Platform: iOS
Build ID: 12
Version: 1669706376
Internal Version: 0
Short Version: 1.0.0
Branch Name: feature/118-flutter-telegram-build-info
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-Flutter-iOS-Dev/releases/12

**Comment by KirBorisov96** [comment]
Platform: iOS
Build ID: 13
Version: 1669708828
Internal Version: 0
Short Version: 1.0.0
Branch Name: feature/118-flutter-telegram-build-info
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-Flutter-iOS-Dev/releases/13

**Comment by KirBorisov96** [comment]
Platform: iOS
Build ID: 14
Version: 1669709981
Internal Version: 0
Short Version: 1.0.0
Branch Name: feature/118-flutter-telegram-build-info
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-Flutter-iOS-Dev/releases/14

**Comment by KirBorisov96** [comment]
> У нас же почти полностью дублируется функционал из admiral_tools? может его там подредачить, если это необходимо, чтобы флаттер мог туда ходить?

> полностью согласен, думаю это надо сделать в рамках другой задачи

**Review by Andyatkov — APPROVED** [review]

**Pull request merged**
